---
- name: "install epel"
  yum:
    name: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
- name: "install nginx"
  yum:
    name: nginx
    state: latest
- name: "put proxy config"
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/conf.d/nginx.conf
- name: "nginx restart"
  service:
    name: nginx
    state: restarted
