---
rmp_telegraf: https://dl.influxdata.com/telegraf/releases/telegraf-1.6.3-1.x86_64.rpm
telegraf_influx_url: http://18.195.50.103:8086
telegraf_influx_database_name: "metrics"
telegraf_influx_database_user: "metrics"
telegraf_influx_database_password: "metrics"
telegraf_hostname: "{{ansible_hostname}}"
telegraf_config_path: "telegraf_default.conf"
metric_storage_ip: 172.31.19.101