---
- hosts: web_nodes
  become: yes
  tags: [web]
  vars:
    my_domain: 54.93.38.173
    proxy_to: ec2-54-93-38-173.eu-central-1.compute.amazonaws.com
  roles:
    - nginx
    - telegraf
  tasks:
    - include_tasks: tasks/os_dependencies.yml
    
- hosts: stats_server
  become: yes
  tags: [stats_server]
  vars:
    metrics_db_name: "metrics"
    metrics_db_pass: "metrics"
    metrics_db_user: "metrics"
    datasource_name: "datasource-influxdb"
    grafana_http_port: 3000
    telegraf_configuration: "telegraf_default.conf"
    ip_adress: "3.122.245.108"
  roles:
    - influxdb
    - grafana
    - telegraf
  tasks:
    - include_tasks: tasks/grafana-config.yml
    
- hosts: app_nodes
  become: yes
  vars:
    jar_location: /home/ec2-user/environment/201600/adsk-ansible-project/carrental/car_rental.jar
    car_rental_jar_remote: /opt/carrental/car_rental.jar
    user: car_rental
    metrics_db_name: "metrics"
    metrics_db_pass: "metrics"
    metrics_db_user: "metrics"
    datasource_name: "datasource-influxdb"
    grafana_http_port: 3000
    telegraf_configuration: "telegraf_default.conf"
    ip_adress: "3.122.245.108"
  roles:
    - app
    - telegraf