---
- name: Create influxdb datasource
  tags: [grafana]
  grafana_datasource:
    name: "{{datasource_name}}"
    grafana_url: "http://{{ip_adress}}:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    ds_type: "influxdb"
    url: "http://{{ip_adress}}:3000"
    database: "{{metrics_db_name}}"
    password: "{{metrics_db_pass}}"
    user: "{{metrics_db_user}}"

- name: "Create directory"
  file:
    path: /var/lib/grafana/dashboards
    state: directory
    
- name: "Copy json file"
  copy:
    src: dashboard/my.json
    dest: /var/lib/grafana/dashboards/my.json
#- template:
 #   src: dashboard/my.json
  #  dest: /tmp/my.json
  #tags: [grafana]
  

- name: Import Grafana dashboard foo
  tags: [grafana, dashboard]
  grafana_dashboard:
    grafana_url: "http://{{ip_adress}}:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    state: present
    uid: mydashboard
    message: Updated by ansible
    overwrite: yes
    path: /var/lib/grafana/dashboards/my.json
  ignore_errors: yes